# Generated by Django 3.2.5 on 2021-07-31 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewsite', '0002_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='images/books'),
        ),
    ]
