# Generated by Django 3.2.5 on 2021-08-08 18:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviewsite', '0004_alter_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='book',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='user_id',
        ),
        migrations.AddField(
            model_name='book',
            name='likes',
            field=models.ManyToManyField(related_name='book_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Dislike',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
