# Generated by Django 3.2.5 on 2021-08-08 18:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviewsite', '0005_auto_20210809_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='dislikes',
            field=models.ManyToManyField(related_name='book_dislikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
